/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BridalCollectionRouteImport } from './routes/bridal-collection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as CustomJewelleryRouteImport } from './routes/custom-jewellery'
import { Route as DiamondCollectionRouteImport } from './routes/diamond-collection'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalCollectionRoute = BridalCollectionRouteImport.update({
  id: '/bridal-collection',
  path: '/bridal-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomJewelleryRoute = CustomJewelleryRouteImport.update({
  id: '/custom-jewellery',
  path: '/custom-jewellery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiamondCollectionRoute = DiamondCollectionRouteImport.update({
  id: '/diamond-collection',
  path: '/diamond-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-collection': typeof BridalCollectionRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/custom-jewellery': typeof CustomJewelleryRoute
  '/diamond-collection': typeof DiamondCollectionRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-collection': typeof BridalCollectionRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/custom-jewellery': typeof CustomJewelleryRoute
  '/diamond-collection': typeof DiamondCollectionRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-collection': typeof BridalCollectionRoute
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/custom-jewellery': typeof CustomJewelleryRoute
  '/diamond-collection': typeof DiamondCollectionRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bridal-collection'
    | '/contact'
    | '/craftsmanship'
    | '/custom-jewellery'
    | '/diamond-collection'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bridal-collection'
    | '/contact'
    | '/craftsmanship'
    | '/custom-jewellery'
    | '/diamond-collection'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bridal-collection'
    | '/contact'
    | '/craftsmanship'
    | '/custom-jewellery'
    | '/diamond-collection'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BridalCollectionRoute: typeof BridalCollectionRoute
  ContactRoute: typeof ContactRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  CustomJewelleryRoute: typeof CustomJewelleryRoute
  DiamondCollectionRoute: typeof DiamondCollectionRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal-collection': {
      id: '/bridal-collection'
      path: '/bridal-collection'
      fullPath: '/bridal-collection'
      preLoaderRoute: typeof BridalCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-jewellery': {
      id: '/custom-jewellery'
      path: '/custom-jewellery'
      fullPath: '/custom-jewellery'
      preLoaderRoute: typeof CustomJewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diamond-collection': {
      id: '/diamond-collection'
      path: '/diamond-collection'
      fullPath: '/diamond-collection'
      preLoaderRoute: typeof DiamondCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BridalCollectionRoute: BridalCollectionRoute,
  ContactRoute: ContactRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  CustomJewelleryRoute: CustomJewelleryRoute,
  DiamondCollectionRoute: DiamondCollectionRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
